---
name: Check Links

on:
  pull_request:
    branches:
      - master

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Requirements
        run: |
          pip install pelican linkchecker

      - name: Start server
        run: |
          make html
          make serve &
          echo $! > server.pid
          sleep 1

      - name: Check links
        run: |
          # some sites forbid robots to access them
          linkchecker --check-extern -f .linkcheckerrc -t 1 \
            http://localhost:8000

      - name: Stop Website Server
        run: |
          kill $(cat server.pid)
